### PR TITLE
feat: add xrpl_info to token

### PR DESCRIPTION
**Pull request by akhlopiachyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Npwz800DCUVfB48Nj4n:-Npwz800DCUVfB48Nj4o:b-dknkgi) (no related file):*
If it is always empty, then why are we even adding it :thinking: 

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Npwz800DCUVfB48Nj4n:-Npy5bqLDB7sLGlw2AMo:b-efeffs) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

If it is always empty, then why are we even adding it :thinking:
</blockquote></details>

I agree with Milad if it is always empty we don't need to add it. 


1. I think presence of `xrpl_info` or `ibc_info` should be optional and we should add these fields only to the tokens which has it. So if token is not ibc or xrpl then we don't even add this attribute at all
2. maybe it makes sense to move all these extra info (specific to token type) to a standalone block. Something like extra
```
...
extra: {
  xrpl_info: {},
  ibc_info: {}
}
...
```
3. probably this PR makes sense once we have at least one example of token with xrpl_info (e.g on testnet) so we can finalize structure fully

Lets discuss this on call

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Npwz800DCUVfB48Nj4n:-NpyKT8_B9RBYRqc3jSx:b-z22zsr) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with Milad if it is always empty we don't need to add it. 


1. I think presence of `xrpl_info` or `ibc_info` should be optional and we should add these fields only to the tokens which has it. So if token is not ibc or xrpl then we don't even add this attribute at all
2. maybe it makes sense to move all these extra info (specific to token type) to a standalone block. Something like extra
```
...
extra: {
  xrpl_info: {},
  ibc_info: {}
}
...
```
3. probably this PR makes sense once we have at least one example of token with xrpl_info (e.g on testnet) so we can finalize structure fully

Lets discuss this on call
</blockquote></details>

1. Agree with @ysv 
2.  Let's keep all together. It's hard to merge and easier to make mistake.
3. I guess it is needed for the development (and devnet only). 

___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Npwz800DCUVfB48Nj4n:-NpyfXjP6-rT3qY4x7xE:b-acwr2f) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

1. Agree with @ysv 
2.  Let's keep all together. It's hard to merge and easier to make mistake.
3. I guess it is needed for the development (and devnet only).
</blockquote></details>

discussed on call

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: all files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`testnet/assets.json` line 52 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq2DQ9W-kI44Wc1pcDL:-Nq2DQ9X3E4fqeshlIKM:b-v8ou1u) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L52)):*
> ```JSON
>             },
>             "extra": {
>                 "xrpl_info": {
> ```

let's remove the "extra" field move this "xrpl_info" to the root of the object. and not touch ibc_info. for all the other tokens that don't have xrpl_info (i.e it will be empty) don't add this field.

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: all files reviewed, 6 unresolved discussions (waiting on @akhlopiachyi, @dzmitryhil, and @wojtek-coreum)

___
*[`testnet/assets.json` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3JO5xARpJFLCWYxAl:-Nq3JO5xARpJFLCWYxAm:b-f1grua) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L29)):*
> ```JSON
>         },
>         {
>             "denom": "xrpl3f36607911-testcore1kpplky98t0mn08z5vc3wa4056dxecczgdvup0wmvgvmwpghsvdrsvz4rfw",
> ```

as for the tokens you add, I don't want to pollute registry (even testnet, devnet is ok to be polluted) with dummy tokens so lets probably limit what we add. Lets add 2-3 popular tokens for now with all proper configs like images, names display names etc. this should be more or less enough for testing.
I suggest official tokens which exist on sologenic DEX. Check here https://sologenic.org/trade?network=testnet&market=XRP%2FUSD%2BrD9W7ULveavz8qBGM1R5jMgK2QKsEDPQVi and make sure to use testnet:
- XRP
- Solo 
- Core
- one of BTC/ETH/USD - I vote for USD



I want our testnet registry to be as close to mainnet as possible. And there are a few issues with these tokens
1.  we will loose keys to their issuers so we will not be able to purchase them later. However for the tokens listed on sologenic there is always enought liquidity
2. they don't exist in real world so there are no images for them etc
___
*[`testnet/assets.json` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3L2bI9ZN2zUCuwJQY:-Nq3L2bI9ZN2zUCuwJQZ:bqctyz3) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L29)):*
> ```JSON
>         },
>         {
>             "denom": "xrpl3f36607911-testcore1kpplky98t0mn08z5vc3wa4056dxecczgdvup0wmvgvmwpghsvdrsvz4rfw",
> ```

continuing previous comment.
I think you might need some custom issued tokens (like this F01, F04 etc) on FE from time to time to test different scenarios. 
To not pollute token registry but still support them inside FE you can just hardcode JSON with this tokens and append them to what you get from registry. And this could be configure using e.g env variable to either include test tokens or not.

This way we will have them on bridge UI and can easily disable and don't pollute token registry
___
*[`testnet/assets.json` line 117 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3HzX00JQhLBWLWgka:-Nq3HzX00JQhLBWLWgkb:bgh9cox) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L117)):*
> ```JSON
>             "extra": {
>                 "xrpl_info": {
>                     "precision": 15,
> ```

AFAIK precision for XRP token is 6 (it is an exception) all others are 15
___
*[`testnet/assets.json` line 118 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3I507BFReFW0mRu5-:-Nq3I507BFReFW0mRu50:bmr3h96) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L118)):*
> ```JSON
>                 "xrpl_info": {
>                     "precision": 15,
>                     "source_chain": "XRPL",
> ```

do we really need it if it is inside xrpl_info than it is obviously XRPL ?
___
*[`testnet/assets.json` line 119 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3LrTgDU-Jvnhc4PRO:-Nq3LrTgDU-Jvnhc4PRP:b-bit5ss) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L119)):*
> ```JSON
>                     "precision": 15,
>                     "source_chain": "XRPL",
>                     "xrpl_issuer": "rDbhhiYb2SMuNUs1Q8udXzAVPUnyHbe3jw",
> ```

for XRP currency there is no real issuer and usually this zero address is used as issuer `rrrrrrrrrrrrrrrrrrrrrhoLvTp` when needed but it should not be displayed on FE

Basically XRP is a bit differet comparing to issued tokens
___
*[`testnet/assets.json` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3IA8R9bHb1QDYZ2Zs:-Nq3IA8S9EmhceKE87Zx:b-fpvkks) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L120)):*
> ```JSON
>                     "source_chain": "XRPL",
>                     "xrpl_issuer": "rDbhhiYb2SMuNUs1Q8udXzAVPUnyHbe3jw",
>                     "currency": "xrp"
> ```

1. I think we should either prefix both of them with xrpl (xrpl_issuer & xrpl_currency or none of them)
2. since these 2 attributes are inside xrpl_info I suggest to not prefix so just issuer & currency



_Code quote:_
```JSON
                    "xrpl_issuer": "rDbhhiYb2SMuNUs1Q8udXzAVPUnyHbe3jw",
                    "currency": "xrp"
```

**Review by akhlopiachyi — COMMENTED** [review]
I fully updated the list of assets for testnet:
- solo
- xrp
- osmo

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-:-NqDwLTw0f6nVrSSbsGj:b-tgjc2k)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`testnet/assets.json` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3JO5xARpJFLCWYxAl:-NqDvGE21T2dbcv7VY0H:b-896fix) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as for the tokens you add, I don't want to pollute registry (even testnet, devnet is ok to be polluted) with dummy tokens so lets probably limit what we add. Lets add 2-3 popular tokens for now with all proper configs like images, names display names etc. this should be more or less enough for testing.
I suggest official tokens which exist on sologenic DEX. Check here https://sologenic.org/trade?network=testnet&market=XRP%2FUSD%2BrD9W7ULveavz8qBGM1R5jMgK2QKsEDPQVi and make sure to use testnet:
- XRP
- Solo 
- Core
- one of BTC/ETH/USD - I vote for USD



I want our testnet registry to be as close to mainnet as possible. And there are a few issues with these tokens
1.  we will loose keys to their issuers so we will not be able to purchase them later. However for the tokens listed on sologenic there is always enought liquidity
2. they don't exist in real world so there are no images for them etc
</blockquote></details>

Done.
___
*[`testnet/assets.json` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3L2bI9ZN2zUCuwJQY:-NqDvgYL3ksjVxvJpaqN:b-896fix) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

continuing previous comment.
I think you might need some custom issued tokens (like this F01, F04 etc) on FE from time to time to test different scenarios. 
To not pollute token registry but still support them inside FE you can just hardcode JSON with this tokens and append them to what you get from registry. And this could be configure using e.g env variable to either include test tokens or not.

This way we will have them on bridge UI and can easily disable and don't pollute token registry
</blockquote></details>

Done.
___
*[`testnet/assets.json` line 117 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3HzX00JQhLBWLWgka:-NqDvhvB5beX5TJnwK7Q:b-896fix) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L117)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

AFAIK precision for XRP token is 6 (it is an exception) all others are 15
</blockquote></details>

Done.
___
*[`testnet/assets.json` line 118 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3I507BFReFW0mRu5-:-NqDvkH-ASXatF0dDC8n:bivxizh) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L118)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really need it if it is inside xrpl_info than it is obviously XRPL ?
</blockquote></details>

To keep consistency of the xrpl assets I would keep it.
One more advantage of having it here is we can define, that this token is native xrp, because it has null address in xrpl issuer
___
*[`testnet/assets.json` line 119 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3LrTgDU-Jvnhc4PRO:-NqDw1SR8r0N3z4UHkCa:b-butns9) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L119)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

maybe it makes sense to add some kind of `is_xrpl: true` or `xrpl: true/false` attribute here ?
since it is a bit different because on all other tokens issuer is requried but for xrpl it is not, also precision is different

maybe it is easier to differentiate it like this

As you prefer
</blockquote></details>

I believe current approach is good enough to handle everything on FE side
___
*[`testnet/assets.json` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3IA8R9bHb1QDYZ2Zs:-NqDwDv56nsHI7j8bzhl:b-e2s8ra) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L120)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. I think we should either prefix both of them with xrpl (xrpl_issuer & xrpl_currency or none of them)
2. since these 2 attributes are inside xrpl_info I suggest to not prefix so just issuer & currency
</blockquote></details>

This token is not in the list anymore

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @dzmitryhil, and @wojtek-coreum)

___
*[`testnet/assets.json` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3IA8R9bHb1QDYZ2Zs:-NqDzH0_BhJUIck4-rW6:b-1svqhe) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L120)):*
<details><summary><i>Previously, akhlopiachyi (Alex Khlopiachyi) wrote…</i></summary><blockquote>

This token is not in the list anymore
</blockquote></details>

but this comment is in general for attribute names
 "xrpl_issuer" -> 'issuer' & keep currency as it is

**Review by akhlopiachyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`testnet/assets.json` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-Nq3IA8R9bHb1QDYZ2Zs:-NqDzgG-36WLcg3kCaSt:b-tazocv) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/b342b05325b4b9d1c5c125d0d0db277b64a590ba/testnet/assets.json#L120)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but this comment is in general for attribute names
 "xrpl_issuer" -> 'issuer' & keep currency as it is
</blockquote></details>

I believe we discussed before, that we would like to separate issuer for coreum and for xrpl
Do you want me to change it to 'issuer'?
___
*[`testnet/assets.json` line 88 at r5](https://reviewable.io/reviews/CoreumFoundation/token-registry/15#-NqDzfUe-BGN47-brPmW:-NqE-CUKBAe4ZgeQUsh3:b-bptrpm) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/5786f3c9a07570953900f6a6b173bc5592d247c6/testnet/assets.json#L88)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

how do you make display name out of this ? do you encode this HEX ? or you have it defined somewhere else ?
</blockquote></details>

I'm taking the display name of the token with next algo:
- in each registered xrpl token I have coreum_denom
- by denom I get the token's metadata and use metadata to display proper names of tokens

That's what we discussed on Tuesday when I raised the question about having token registry for xrpl tokens

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/15)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
