### PR TITLE
fixes incorrect files - assets.json by adding new token details

### PR DESCRIPTION
**Pull request by elix1er**
.. for CCD, including metadata such as description, logo URIs, and social media links.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/38)

Replaces #37

### CODE REVIEW

**Comment by CoreumCommunityDAO** [comment]
Thanks looks good, LGTM

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Comment by tokenizin** [comment]
bump

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Comment by elix1er** [comment]
bump @dzmitryhil @ysv 🙏🏻

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Comment by tokenizin** [comment]
bump

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Pull request merged**
