### PR TITLE
Update assets.json

### PR DESCRIPTION
**Pull request by chasemerlin**
Add SBC to Assets

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/36)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/36)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Comment by chasemerlin** [comment]
@miladz68 Updated.

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/36)* status: all files reviewed, 1 unresolved discussion (waiting on @chasemerlin, @masihyeganeh, and @ysv)

**Review by ysv — APPROVED** [review]

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/36)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Review by miladz68 — APPROVED** [review]
Approved.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/36#-:-OCCeEzu3HHe19utIgCB:bnjjt6g)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Pull request merged**
