### PR TITLE
Added info for the coreum token

### PR DESCRIPTION
**Pull request by miladz68**
In this PR we add the information for Coreum token into the registry

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/1)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @akhlopiachyi, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @miladz68, @wojtek-coreum, and @ysv)

___
*[`assets.json` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/token-registry/1#-NjMIaL6Berm8BoGHSSv:-NjMIaL6Berm8BoGHSSw:b-fhokl6) ([raw file](https://github.com/coreumfoundation/token-registry/blob/4c47b9391eb4dc48376de54abad9f234eeca5d2f/assets.json#L30)):*
> ```JSON
>         }
>     ]
> }
> ```

New line?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`assets.json` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/token-registry/1#-NjMIaL6Berm8BoGHSSv:-NjMKXda7s3UgeBkYMHP:b-896fix) ([raw file](https://github.com/coreumfoundation/token-registry/blob/4c47b9391eb4dc48376de54abad9f234eeca5d2f/assets.json#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

New line?
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: all files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi, @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/token-registry/1#-NjN2XPg1MCricC1xWoo:-NjN2XPg1MCricC1xWop:b-u6l7r3) (no related file):*
Is this registry updated by us only or 3rd parties will make PRs too in the future?

___

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: all files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi, @dzmitryhil, @miladz68, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: all files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi and @miladz68)

___
*[`assets.json` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/token-registry/1#-NjO-md5-7IckwPvxOIt:-NjO-md5-7IckwPvxOIu:b5pkl8i) ([raw file](https://github.com/coreumfoundation/token-registry/blob/0d9c63a0cea1a3bb871bf0c8f3dcce6eeca57930/assets.json#L1)):*
> ```JSON
> {
> ```

if you can ask Reza to review this would probably be also nice
To make sure it is what he expects
___
*[`assets.json` line 6 at r3](https://reviewable.io/reviews/coreumfoundation/token-registry/1#-NjO-c9B8E0TU9VGQdd_:-NjO-c9C3hxV5MYmS32t:bpprbv7) ([raw file](https://github.com/coreumfoundation/token-registry/blob/0d9c63a0cea1a3bb871bf0c8f3dcce6eeca57930/assets.json#L6)):*
> ```JSON
>             "denom": "ucore",
>             "ibc_info": {
>                 "display_name": "Core",
> ```

should it be `Core` or `CORE`

I'm also confused which name we should use core or coreum because e.g in osmosis it is COREUM

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/token-registry/1#-NjN2XPg1MCricC1xWoo:-NjRJzXQ2JfTOfntEjag:b9uyv2d) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is this registry updated by us only or 3rd parties will make PRs too in the future?
</blockquote></details>

third parties will make PRs. 

___
___
*[`assets.json` line 6 at r3](https://reviewable.io/reviews/coreumfoundation/token-registry/1#-NjO-c9B8E0TU9VGQdd_:-NjRKBdz7zhgCtUgrolM:b-epo452) ([raw file](https://github.com/coreumfoundation/token-registry/blob/0d9c63a0cea1a3bb871bf0c8f3dcce6eeca57930/assets.json#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should it be `Core` or `CORE`

I'm also confused which name we should use core or coreum because e.g in osmosis it is COREUM
</blockquote></details>

`CORE` makes more sense I guess.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi, @wojtek-coreum, and @ysv)

___
*[`assets.json` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/token-registry/1#-NjO-md5-7IckwPvxOIt:-NjRs9Fx6K9Gku-Wxkug:bpzw1p6) ([raw file](https://github.com/coreumfoundation/token-registry/blob/0d9c63a0cea1a3bb871bf0c8f3dcce6eeca57930/assets.json#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

if you can ask Reza to review this would probably be also nice
To make sure it is what he expects
</blockquote></details>

Done. he requested 2 changes that I applied.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @akhlopiachyi)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @akhlopiachyi)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/token-registry/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @akhlopiachyi)

**Pull request merged**
