### PR TITLE
fix: update chain name for osmo in testnet

### PR DESCRIPTION
**Pull request by akhlopiachyi**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @miladz68, @wojtek-coreum, and @ysv)

___
*[`testnet/assets.json` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/token-registry/18#-NsCLG3r1hRFVW2hv2Y3:-NsCLG3r1hRFVW2hv2Y4:b-2y563d) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/12dda64faf47fcde27d5776fcc0505a280b3ca6f/testnet/assets.json#L123)):*
> ```JSON
>                     "display_name": "OSMO",
>                     "precision": 6,
>                     "source_chain": "Osmosistestnet",
> ```

Why do you need that?

**Review by ysv — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @miladz68, and @wojtek-coreum)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi and @wojtek-coreum)

**Review by akhlopiachyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`testnet/assets.json` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/token-registry/18#-NsCLG3r1hRFVW2hv2Y3:-NsHczKgCgR7fya7CeUb:b-1jxdx7) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/12dda64faf47fcde27d5776fcc0505a280b3ca6f/testnet/assets.json#L123)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need that?
</blockquote></details>

To define correct ibc denom of the chain, I need correct chain name
There isn’t a chain with name osmosis in testnet chains in chain registry
But there is osmosistestnet

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18#-:-Nsfyq0IBCx-SH2sZumu:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @akhlopiachyi)

**Pull request merged**
